from ..codenames import (
    rando,
    ae_review,
    ae,
    everyone,
    data_manager,
    data_query,
    export,
    lab,
    lab_view,
    pharmacy,
    site_data_manager,
    account_manager,
    administration,
    auditor,
    celery_manager,
    clinic,
    pii,
    pii_view,
    screening,
)
from ..group_names import (
    ACCOUNT_MANAGER,
    ADMINISTRATION,
    AE,
    AE_REVIEW,
    AUDITOR,
    CELERY_MANAGER,
    CLINIC,
    DATA_MANAGER,
    DATA_QUERY,
    EVERYONE,
    EXPORT,
    LAB,
    LAB_VIEW,
    PHARMACY,
    PII,
    PII_VIEW,
    RANDO,
    SCREENING,
    SITE_DATA_MANAGER,
)

default_codenames = {
    ACCOUNT_MANAGER: account_manager,
    ADMINISTRATION: administration,
    AE: ae,
    AE_REVIEW: ae_review,
    AUDITOR: auditor,
    CELERY_MANAGER: celery_manager,
    CLINIC: clinic,
    DATA_MANAGER: data_manager,
    DATA_QUERY: data_query,
    EVERYONE: everyone,
    EXPORT: export,
    LAB: lab,
    LAB_VIEW: lab_view,
    PHARMACY: pharmacy,
    PII: pii,
    PII_VIEW: pii_view,
    RANDO: rando,
    SCREENING: screening,
    SITE_DATA_MANAGER: site_data_manager,
}
