from .codenames import (
    account_manager,
    administration,
    ae,
    ae_review,
    auditor,
    celery_manager,
    clinic,
    clinic_super,
    dispensing,
    everyone,
    export,
    lab,
    lab_view,
    pharmacy,
    pii,
    pii_view,
    review,
    statistician,
    tmg,
    tmg_review,
)
from .default_group_names import (
    ACCOUNT_MANAGER,
    ADMINISTRATION,
    AE,
    AE_REVIEW,
    AUDITOR,
    CELERY_MANAGER,
    CLINIC,
    CLINIC_SUPER,
    DISPENSING,
    EVERYONE,
    EXPORT,
    LAB,
    LAB_VIEW,
    PHARMACY,
    PII,
    PII_VIEW,
    REVIEW,
    STATISTICIAN,
    TMG,
    TMG_REVIEW,
)

default_groups = {
    AE: ae,
    AE_REVIEW: ae_review,
    ACCOUNT_MANAGER: account_manager,
    ADMINISTRATION: administration,
    AUDITOR: auditor,
    CELERY_MANAGER: celery_manager,
    CLINIC: clinic,
    CLINIC_SUPER: clinic_super,
    DISPENSING: dispensing,
    EVERYONE: everyone,
    EXPORT: export,
    LAB: lab,
    LAB_VIEW: lab_view,
    PHARMACY: pharmacy,
    PII: pii,
    PII_VIEW: pii_view,
    REVIEW: review,
    STATISTICIAN: statistician,
    TMG: tmg,
    TMG_REVIEW: tmg_review,
}
