from .codenames import (
    account_manager,
    administration,
    auditor,
    celery_manager,
    clinic,
    clinic_super,
    dispensing,
    everyone,
    export,
    pharmacy,
    pii,
    pii_view,
    review,
    statistician,
)
from .default_group_names import (
    ACCOUNT_MANAGER,
    ADMINISTRATION,
    AUDITOR,
    CELERY_MANAGER,
    CLINIC,
    CLINIC_SUPER,
    DISPENSING,
    EVERYONE,
    EXPORT,
    PHARMACY,
    PII,
    PII_VIEW,
    REVIEW,
    STATISTICIAN,
)

default_groups = {
    ACCOUNT_MANAGER: account_manager,
    ADMINISTRATION: administration,
    AUDITOR: auditor,
    CELERY_MANAGER: celery_manager,
    CLINIC: clinic,
    CLINIC_SUPER: clinic_super,
    DISPENSING: dispensing,
    EVERYONE: everyone,
    EXPORT: export,
    PHARMACY: pharmacy,
    PII: pii,
    PII_VIEW: pii_view,
    REVIEW: review,
    STATISTICIAN: statistician,
}
