ACCOUNT_MANAGER = "ACCOUNT_MANAGER"
ADMINISTRATION = "ADMINISTRATION"
AE = "AE"
AE_REVIEW = "AE_REVIEW"
AUDITOR = "AUDITOR"
CELERY_MANAGER = "CELERY_MANAGER"
CLINIC = "CLINIC"
DATA_MANAGER = "DATA_MANAGER"
SITE_DATA_MANAGER = "SITE_DATA_MANAGER"
DATA_QUERY = "DATA_QUERY"
EVERYONE = "EVERYONE"
EXPORT = "EXPORT"
LAB = "LAB"
LAB_VIEW = "LAB_VIEW"
PHARMACY = "PHARMACY"
PII = "PII"
PII_VIEW = "PII_VIEW"
RANDO = "RANDO"
REVIEW = "REVIEW"
SCREENING = "SCREENING"
TMG = "TMG"
UNBLINDING_REQUESTORS = "UNBLINDING_REQUESTORS"
UNBLINDING_REVIEWERS = "UNBLINDING_REVIEWERS"

DEFAULT_GROUP_NAMES = [
    ACCOUNT_MANAGER,
    ADMINISTRATION,
    AE,
    AE_REVIEW,
    AUDITOR,
    CELERY_MANAGER,
    CLINIC,
    DATA_MANAGER,
    DATA_QUERY,
    SITE_DATA_MANAGER,
    EVERYONE,
    EXPORT,
    LAB,
    LAB_VIEW,
    PHARMACY,
    PII,
    PII_VIEW,
    RANDO,
    REVIEW,
    SCREENING,
]
